config/routes.rb
Rails.application.routes.draw do

# 管理者用
# URL /admin/sign_in ...
  devise_for :admin,skip:[:registrations,:passwords],controllers:{
    sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


  namespace :admin do

    root to: 'homes#top'

    resources :items ,only:[:index, :new, :create, :show, :edit, :update]

    resources :genres ,only:[:index, :create, :edit, :update]

    resources :customers ,only:[:index, :show, :edit, :update] #顧客一覧など

    resources :orders ,only:[:show, :update]

    patch '/orders/:order_id/order_details/:id' => 'order_details#update' #製作ステータスの更新　　もしくはネストはなくてもよい /admin/order_details/:id

  end

# 顧客用
# URL /customers/sign_in ...
  devise_for :customers,skip:[:passwords],controllers:{
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

    scope module: :public do

    root to: 'homes#top'
    get '/about' => 'homes#about' ,as: 'about'

    resources :items ,only:[:index, :show]

    get '/customers/my_page' => 'customers#show'
    get '/customers/information/edit' => 'customers#edit' #顧客の登録情報編集画面
    patch 'customers/information' => 'customers#update' #顧客の登録情報更新
    get '/customers/unsubscribe' => 'customers#unsubscribe' #顧客の退会確認画面
    patch '/customers/withdraw' => 'customers#withdraw' #顧客の退会処理(ステータスの更新)

    delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items ,only:[:index, :update, :create, :destroy]

    get '/orders/complete' => 'orders#complete' #注文完了画面
    resources :orders ,only:[:new, :index, :show, :create]
    post '/orders/confirm' => 'orders#confirm' #注文情報確認画面


    resources :addresses ,only:[:index, :edit, :create, :update, :destroy] #配送先情報など

  end

end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer
  
def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
end
  
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  validates :item_id, :amount, presence: true
  validates :amount, numericality: {greater_than: 0,less_than_or_equal: 10} #左記は10以下　less_thanは未満
  validates :amount, numericality:{ only_integer: true }

  def sum_price # 税込価格を算出したメソッドを定義して呼び出す taxin_priceは item.rb（税込価格)に定義
      item.with_tax_price * amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items ,dependent: :destroy
  has_many :orders ,dependent: :destroy
  has_many :addresses ,dependent: :destroy

  def full_name
    last_name+first_name
  end

  def full_name_kana
    last_name_kana+first_name_kana
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy

  validates :name, presence: true
  validates :name, {uniqueness: true}
end

#バリデーション　（モデル、view、コントローラーに記述）

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  belongs_to :genre

   def get_image(width,height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpg')
    end
    image.variant(resize_to_limit: [width, height]).processed
   end

   def with_tax_price
    (price * 1.1).floor
   end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy

  attribute :shipping_cost, :integer, default: 800


  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { waiting_payment: 0, payment_confirmation:1, production:2, preparing_to_ship:3, sent:4 }

  def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
  end

  def payment
    shipping_cost + total_payment
  end

  def full_name
    customer.last_name + customer.first_name
  end

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  enum making_status: {no_make: 0, make_wait: 1, making: 2, make_fin: 3}

  def sum_price # 税込価格を算出したメソッドを定義して呼び出す taxin_priceは item.rb（税込価格)に定義
      (price * 1.1).floor * amount
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])

  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      flash[:notice] = "You have updated book successfully."
    redirect_to admin_customer_path(@customer.id)
    else
    render :edit
    end
  end

  private
  def customer_params #privateメソッドの名前は、「モデル名_params」とすることが多い
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email, :is_deleted) #bookはモデルのtitle.bodyカラムを承認
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres =Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
     redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end
  def update
    @genre =Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end

  private
   def genre_params
    params.require(:genre).permit(:name)
   end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top  #注文履歴一覧（adminのtop）
    @orders = Order.page(params[:page])
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end

  def index
    @item = Item.page(params[:page])

  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_items_path
  end

  private
   def item_params
    params.require(:item).permit(:name, :image, :introduction, :genre_id, :price, :is_active)
   end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @order_detail = @order.order_details
  end

  def update
    @order = Order.find(params[:id])
    if @order.update(order_params)
      if @order.status == "payment_confirmation" #1は入金確認
         @order.order_details.each do |order_detail|
           order_detail.update(making_status: 1)
         end
      end
      redirect_to admin_order_path(@order.id)
    else
      render :show
    end
  end

  private
  def order_params
      params.require(:order).permit(:status)
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/customers/edit.html.erb
<div class = "container">
 <div class = "row">
  <div class ="col-5 bg-secondary">
   <h2><%= @customer.full_name %>さんの会員情報編集</h2>
  </div>
 </div>
</div>
   <div class = "row text-center mt-5" >
    <div class = "col-8" >
     <table class = "table">
         <%= form_with model: @customer, url: admin_customer_path(@customer.id), method: :patch do |f| %>
       <tr>
        <td><%= f.label "会員ID" %></td>
        <td><%= @customer.id %></td>
       </tr>
       <tr>
        <td><%= f.label "氏名" %></td>
        <td><%= f.text_field :last_name ,class: "form-control" %></td>
        <td><%= f.text_field :first_name ,class: "form-control" %></td>
       </tr>
       <tr>
        <td><%= f.label "フリガナ" %></td>
        <td><%= f.text_field :last_name_kana ,class: "form-control" %></td>
        <td><%= f.text_field :first_name_kana ,class: "form-control" %></td>
       </tr>
       <tr>
        <td><%= f.label "郵便番号" %></td>
        <td><%= f.text_field :postal_code ,class: "form-control" %></td>
       </tr>
       <tr>
        <td><%= f.label "住所" %></td>
        <td><%= f.text_field :address ,class: "form-control" %></td>
       </tr>
       <tr>
        <td><%= f.label "電話番号" %></td>
        <td><%= f.text_field :telephone_number ,class: "form-control" %></td>
       </tr>
       <tr>
        <td><%= f.label "メールアドレス" %></td>
        <td><%= f.text_field :email ,class: "form-control" %></td>
       </tr>
       <tr>
        <td><%= f.label "会員ステータス" %></td>
        <td>
        <%= f.label '退会' %>
        <%= f.radio_button :is_deleted, true %>
        <%= f.label "is_deleted",'有効', value: false %> <%# 47,50は同じ意味 %>
        <%= f.radio_button :is_deleted, 'false' %>
        </td>
       </tr>
       <tr>
        <td></td>
        <td><%= f.submit "変更を保存" ,class: "btn btn-success" %></td>
       </tr>
         <% end %>
     </table>
    </div>
   </div>

app/views/admin/customers/index.html.erb
 <div class ="container">
   <div class ="row mb-3" >
    <h1>会員一覧</h1>
   </div>
    <table class = "table">
     <div class "col">
      <thead class ="bg-light">
       <tr>
        <th>会員ID</th>
        <th>氏名</th>
        <th>メールアドレス</th>
        <th>ステータス</th>
       </tr>
      </thead>
      <tbody>
       <% @customers.each do |customer| %>
       <tr>
        <td><%= customer.id %></td>
        <td><u><%= link_to customer.full_name ,admin_customer_path(customer.id) %></u></td>
        <td><%= customer.email %></td>
        <td>
         <% if customer.is_deleted %>
          <p class ="text-secondary font-weight-bold">退会</p>
         <% else %>
          <p class ="text-success font-weight-bold">有効</p>
         <% end %>
        </td>
       </tr>
       <% end %>
      </tbody>
     </div>
    </table>
    <div class ="row">
     <div class ="mx-auto">
      <%= paginate @customers %>
     </div>
    </div>
  </div>

app/views/admin/customers/show.html.erb
<div class = "container">
 <div class = "row">
  <div class ="col-5">
   <h2><%= @customer.full_name %>さんの会員詳細</h2>
  </div>
 </div>
</div>
   <div class = "row text-center mt-5">
    <div class = "col">
      <table class = "table">
        <tr>
         <td><%= "会員ID" %></td>
         <td><%= @customer.id %></td>
        </tr>
        <tr>
         <td><%= "氏名" %></td>
         <td><%= @customer.full_name %></td>
        </tr>
        <tr>
         <td><%= "フリガナ" %></td>
         <td><%= @customer.full_name_kana %></td>
        </tr>
        <tr>
         <td><%= "郵便番号" %></td>
         <td><%= @customer.postal_code %></td>
        </tr>
        <tr>
         <td><%= "住所" %></td>
         <td><%= @customer.address %></td>
        </tr>
        <tr>
         <td><%= "電話番号" %></td>
         <td><%= @customer.telephone_number %></td>
        </tr>
        <tr>
         <td><%= "メールアドレス" %></td>
         <td><%= @customer.email %></td>
        </tr>
        <tr>
         <td><%= "会員ステータス" %></td>
         <td><% if @customer.is_deleted %>
              <p class = "text-secondary">退会</p>
             <% else %>
              <P class = "text-success">有効</P>
             <% end %>
         </td>
        </tr>
        <tr>
         <td></td>
         <td><%= link_to "編集する" , edit_admin_customer_path(@customer.id) ,class: "btn btn-success" %></td>
         <td class="text-left"><%= link_to "注文履歴一覧を見る" , admin_order_path ,class: "btn btn-primary" %></td>
         <td></td>
        </tr>
      </table>
     </div>
    </div>