config/routes.rb
Rails.application.routes.draw do

# 管理者用
# URL /admin/sign_in ...
  devise_for :admin,skip:[:registrations,:passwords],controllers:{
    sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


  namespace :admin do

    root to: 'homes#top'

    resources :items ,only:[:index, :new, :create, :show, :edit, :update]

    resources :genres ,only:[:index, :create, :edit, :update]

    resources :customers ,only:[:index, :show, :edit, :update] #顧客一覧など

    resources :orders ,only:[:show, :update]

    patch '/orders/:order_id/order_details/:id' => 'order_details#update' #製作ステータスの更新　　もしくはネストはなくてもよい /admin/order_details/:id

  end

# 顧客用
# URL /customers/sign_in ...
  devise_for :customers,skip:[:passwords],controllers:{
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

    scope module: :public do

    root to: 'homes#top'
    get '/about' => 'homes#about' ,as: 'about'

    resources :items ,only:[:index, :show]

    get '/customers/my_page' => 'customers#show'
    get '/customers/information/edit' => 'customers#edit' #顧客の登録情報編集画面
    patch 'customers/information' => 'customers#update' #顧客の登録情報更新
    get '/customers/unsubscribe' => 'customers#unsubscribe' #顧客の退会確認画面
    patch '/customers/withdraw' => 'customers#withdraw' #顧客の退会処理(ステータスの更新)

    delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items ,only:[:index, :update, :create, :destroy]

    get '/orders/complete' => 'orders#complete' #注文完了画面
    resources :orders ,only:[:new, :index, :show, :create]
    post '/orders/confirm' => 'orders#confirm' #注文情報確認画面


    resources :addresses ,only:[:index, :edit, :create, :update, :destroy] #配送先情報など

  end

end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer
  
def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
end
  
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  validates :item_id, :amount, presence: true
  validates :amount, numericality: {greater_than: 0,less_than_or_equal: 10} #左記は10以下　less_thanは未満
  validates :amount, numericality:{ only_integer: true }

  def sum_price # 税込価格を算出したメソッドを定義して呼び出す taxin_priceは item.rb（税込価格)に定義
      item.with_tax_price * amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items ,dependent: :destroy
  has_many :orders ,dependent: :destroy
  has_many :addresses ,dependent: :destroy

  def full_name
    last_name+first_name
  end

  def full_name_kana
    last_name_kana+first_name_kana
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy

  validates :name, presence: true
  validates :name, {uniqueness: true}
end

#バリデーション　（モデル、view、コントローラーに記述）

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  belongs_to :genre

   def get_image(width,height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpg')
    end
    image.variant(resize_to_limit: [width, height]).processed
   end

   def with_tax_price
    (price * 1.1).floor
   end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy

  attribute :shipping_cost, :integer, default: 800


  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { waiting_payment: 0, payment_confirmation:1, production:2, preparing_to_ship:3, sent:4 }

  def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
  end

  def payment
    shipping_cost + total_payment
  end

  def full_name
    customer.last_name + customer.first_name
  end

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  enum making_status: {no_make: 0, make_wait: 1, making: 2, make_fin: 3}

  def sum_price # 税込価格を算出したメソッドを定義して呼び出す taxin_priceは item.rb（税込価格)に定義
      (price * 1.1).floor * amount
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres =Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
     redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end
  def update
    @genre =Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end

  private
   def genre_params
    params.require(:genre).permit(:name)
   end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top  #注文履歴一覧（adminのtop）
    @orders = Order.page(params[:page])
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end

  def index
    @item = Item.page(params[:page])

  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_items_path
  end

  private
   def item_params
    params.require(:item).permit(:name, :image, :introduction, :genre_id, :price, :is_active)
   end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @order_detail = @order.order_details
  end

  def update
    @order = Order.find(params[:id])
    if @order.update(order_params)
      if @order.status == "payment_confirmation" #1は入金確認
         @order.order_details.each do |order_detail|
           order_detail.update(making_status: 1)
         end
      end
      redirect_to admin_order_path(@order.id)
    else
      render :show
    end
  end

  private
  def order_params
      params.require(:order).permit(:status)
  end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  #before_action :configure_permitted_parameters, if: :devise_controller?



  def after_sign_in_path_for(resource)
    admin_root_path
  end

  def after_sign_out_path_for(resource)
    new_admin_session_path
  end



  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/edit.html.erb
 <div class ="container">
  <div class = "row">
   <div class ="col-4">
   <h1>ジャンル編集</h1>
     <%= form_with model: @genre, url: admin_genre_path(@genre.id) ,method: :patch do |f| %>
    <label for = "inputName">ジャンル名</label>
    <%= f.text_field :name ,class: "form-control name" %><br>
    <%= f.submit "変更を保存" ,class: "btn btn-success" %>
    <% end %>
   </div>
  </div>
 </div>
    

app/views/admin/genres/index.html.erb
 <div class = "container">
  <div class = "row mb-5">
    <h1>ジャンル一覧・追加</h1>
  </div>
  <%= form_with model: @genre, url: admin_genres_path ,method: :post do |f| %>
  <div class = "row">
  <table class = "table">
     <tr>
      <td><%= f.label "ジャンル名" %></td>
      <td><%= f.text_field :name ,class: "form-control genre_name", :placeholder => "ジャンル名" %></td>
      <td><%= f.submit "新規登録" ,class: "btn btn-success" %></td>
     </tr>
  </table>
  </div>
  <% end %>
  <div class = "row" >
   <div class = "col-4">
    <table class ="table">
     <thead>
      <tr>
       <th>ジャンル</th>
      </tr>
     </thead>
     <% @genres.each do |genre| %>
     <tbody>
      <tr>
       <td><%= genre.name %></td>
       <td><%= link_to "編集する" ,edit_admin_genre_path(genre.id) ,class: "btn btn-success" %></td>
      </tr>
     </tbody>
     <% end %>
    </table>
   </div>
  </div>
 </div>

app/views/admin/items/edit.html.erb
<div class = "container" >
 <div class = "row" >
  <div class ="col-auto" >
   <h1>商品編集</h1>
  </div>
     <%= form_with model: @item ,url: admin_item_path(@item.id) , method: :patch do |f| %>

      <%= f.label "商品画像" %>
      <%= f.file_field :image, class: "form-control-file" %><br> <%# imageはカラム名（has_one_attached）と同じ %>

      <%= f.label "商品名" %><br>
      <%= f.text_field :name, class: "form-control item_name" %><br>

      <%= f.label "商品説明" %><br>
      <%= f.text_area :introduction, class: "form-control item_explanation" %><br> <%# explanation(説明) %>


      <%= f.label "ジャンル" %><br>
      <%= f.select :genre_id, options_from_collection_for_select(Genre.all, :id, :name) ,{include_blank: '--選択して下さい--'} %><br>
      <%#= f.select :genre_id, ['ケーキ','プリン','焼き菓子','キャンディ'], {include_blank: '--選択して下さい--'} %>

      <%= f.label "税抜価格" %><br>
      <%= f.text_field :price , class: "form-controll"  %><br>

      <%= f.label '販売ステータス' %><br>
      <%= f.label "is_active",'販売中', value: true %>
      <%= f.radio_button :is_active, 'true' %>
      <%= f.label "is_active",'販売停止中', value: false %>
      <%= f.radio_button :is_active, 'false' %><br>
      <%= f.submit "変更を保存" ,class: "btn btn-success" %>
     <% end %>
   </div>

app/views/admin/items/index.html.erb
  <div class ="container">
    <div class ="row mb-3" >
     <div class = "col-4">
      <h1>商品一覧</h1>
     </div>
     <div class ="col-8 text-right" >
      <%= link_to new_admin_item_path, class: 'btn btn-default' do %>
       <i class="fa fa-arrow-up"></i>
      <% end %>
     </div>
    </div>
     <div class = "row">
     <table class = "table" >
      <div class "col">
       <thead>
        <tr>
         <th>商品ID</th>
         <th>商品名</th>
         <th>税抜価格</th>
         <th>ジャンル</th>
         <th>ステータス</th>
        </tr>
       </thead>
       <tbody>
        <% @item.each do |item| %>
        <tr>
         <td><%= item.id %></td>
         <td><u><%=link_to item.name ,admin_item_path(item.id) %></u></td>
         <td><%= item.price %>円</td>
         <td>
          <%#= Genre.find(item.genre_id).name %> <%# idを使ってジャンルを探す %>
          <%= item.genre.name %> <%# リレーションを使ったやり方 %>
         </td>
         <td>
          <% if item.is_active %>
           <p class ="text-success font-weight-bold">販売中</p>
          <% else %>
           <p class ="text-secondary font-weight-bold">販売停止中</p>
          <% end %>
         </td>
        </tr>
        <% end %>
       </tbody>
      </div>
     </table>
     </div>
    <div class ="row">
     <div class ="mx-auto">
    <%= paginate @item %>
     </div>
    </div>
 </div>

app/views/admin/items/new.html.erb
 <div class = "container" >
  <div class = "row" >
   <div class ="col-auto" >
    <h1>商品新規登録</h1>
   </div>
  </div>
  <div class = "row mt-5">
   <div class = "mx-auto">
     <%#= form_with model:[:admin,@item], method: :post do |f| %>
    <%= form_with model: @item ,url: admin_items_path,  method: :post do |f| %>
     <table class ="table">
       <tr>
        <td><%= f.label "商品画像" %></td>
        <td><%= f.file_field :image, class: "form-control-file" %></td> <%# imageはカラム名（has_one_attached）と同じ %>
       </tr>
       <tr>
        <td><%= f.label "商品名" %></td>
        <td><%= f.text_field :name, class: "form-control item_name", :placeholder => "商品名" %></td>
       </tr>
        <tr>
         <td><%= f.label "商品説明" %></td>
         <td><%= f.text_area :introduction, class: "form-control item_explanation" , :placeholder => "ここに説明文を記述します" %></td> <%# explanation(説明) %>
       </tr>
       <tr>
        <td><%= f.label "ジャンル" %></td>
        <td><%= f.select :genre_id, options_from_collection_for_select(Genre.all, :id, :name), {include_blank: '--選択して下さい--'} %></td>
       </tr>
        <%#= f.select :genre_id, ['ケーキ','プリン','焼き菓子','キャンディ'], {include_blank: '--選択して下さい--'} %>
       <tr>
        <td><%= f.label "税抜価格" %></td>
        <td><%= f.text_field :price , class: "form-controll price" , :placeholder => "1000" %>円</td>
       </tr>
       <tr>
        <td><%= f.label '販売ステータス' %></td>
        <td>
         <%= f.label "is_active",'販売中', value: true %>
         <%= f.radio_button :is_active, 'true' %>
         <%= f.label "is_active",'販売停止中', value: false %>
         <%= f.radio_button :is_active, 'false' %>
        </td>
       </tr>
     </table>
      <div class ="row">
       <div class ="mx-auto">
        <%= f.submit "新規登録",class: "btn btn-success" %>
       </div>
      </div>
   </div>
  </div>
   <% end %>
 </div>

app/views/admin/items/show.html.erb
 <div class = "container" >
  <div class = "row">
   <h1>商品詳細</h1>
  </div>
  <div class = "row">
     <div class ="col-4 d-flex align-items-center justify-content-center">
          <%= link_to admin_item_path(@item.id) do %>
          <%= image_tag @item.get_image(100,100) %>
          <% end %>
     </div>
  <div class ="col-8">
    <table class='table'>
     <tr>
      <td><%= "商品名" %></td>
      <td><%= @item.name %></td>
     </tr>
     <tr>
      <td><%= "商品説明" %></td>
      <td><%= @item.introduction %></td>
     </tr>
     <tr>
      <td><%= "ジャンル" %></td>
      <td><%= @item.genre.name %></td>
     </tr>
     <tr>
      <td>
          <%= "税込価格" %><br>
          <%= "（税抜価格）" %>
      </td>
      <td>
          <%= @item.with_tax_price %>
          (<%= @item.price %>)円
      </td>
     </tr>
     <tr>
      <td><%= "販売ステータス" %></td>
      <td>
       <% if @item.is_active %>
        <p class ="text-success font-weight-bold">販売中</p>
       <% else %>
        <p class ="text-secondary font-weight-bold"><p>販売停止中</p>
       <% end %>
      </td>
     </tr>
    </table>
    </div>
  </div>
    <div class = "col text-center" >
     <%= link_to "編集する" , edit_admin_item_path(@item.id) ,class: "btn btn-success btn-lg" %>
    </div>
 </div>

app/views/admin/orders/show.html.erb
   <div class ="container">
     <div class ="row mb-3" >
      <h3>注文履歴詳細(admin)</h3>
     </div>
     <div class ="row">
      <div class ="col-6">
       <table class = "table">
         <tr>
          <td class ="font-weight-bold"><%= "購入者" %></td>
          <td><%= link_to @order.full_name ,admin_customer_path(@order.id) %></td>
         </tr>
         <tr>
          <td class ="font-weight-bold"><%= "注文日" %></td>
          <td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
         </tr>
         <tr>
          <td class ="font-weight-bold"><%= "配送先" %></td>
          <td><%= @order.address_display %></td> <%# amountはどこからもってくる？ %>
         </tr>
         <tr>
          <td class ="font-weight-bold"><%= "支払い方法" %></td>
          <td><%= @order.payment_method_i18n %></td>
         </tr>
         <tr>
          <td class ="font-weight-bold"><%= "注文ステータス" %></td>
          <td>
              <%= form_with model: @order, url: admin_order_path(@order.id), method: :patch ,local: true, class: "form" do |f| %>
              <%= f.select :status, Order.statuses_i18n.invert, class: "order_status" %>
              <%= f.submit "更新",class: "btn btn-success"%>
          </td>
         </tr>
              <% end %>
       </table>
      </div>
     </div>
     <div class ="row">
      <div class = "col-9">
       <table class = "table">
         <thead>
          <tr>
            <th>商品名</th>
            <th>単価（税込）</th>
            <th>数量</th>
            <th>小計</th>
            <th>製作ステータス</th>
          </tr>
         </thead>
              <% @order_detail.each do |order_detail| %>
         <tbody>
          <tr>
           <td><%= order_detail.item.name %></td><!-- 商品名 -->
           <td><%= order_detail.item.with_tax_price %>円</td> <!-- 金額 -->
           <td><%= order_detail.amount %></td> <!-- 個数 -->
           <td><%= order_detail.sum_price %>円</td><!-- 小計 -->
           <td> <%# urlのidが二つある場合（ネストしているため下記のような書き方になる %>
               <%= form_with  model: order_detail ,url: admin_path(@order.id,order_detail.id) ,method: :patch do |f| %> <%# model: [@order,order_detail] %> <%# ネストしているための書き方(@order.id,order_detail.id) %>
                <%#= f.select :making_status,[["製作不可",0],["製作待ち",1],["製作中",2],["製作完了",3]] %>
                <%= f.select :making_status, OrderDetail.making_statuses_i18n.invert, class: "order_detail_status" %>
                <%= f.submit "更新" ,class: "btn btn-success" %>
               <% end %>
           </td>
          </tr>
         </tbody>
              <% end %>
       </table>
      </div>
       <div class = "col-3" >
        <table class ="table">
        <tr>
         <td>
          <p class ="font-weight-bold">商品合計</p>
           <td><%= @order.payment %>円</td>
         </td>
        </tr>
        <tr>
         <td>
          <p class ="font-weight-bold">送料</p>
           <td><%= @order.shipping_cost %>円</td>
         </td>
        </tr>
        <tr>
         <td>
          <p class ="font-weight-bold">請求金額合計</p>
           <td><%= @order.payment + @order.shipping_cost %>円</td>
         </td>
        </tr>
        </table>
       </div>
      </div>
     </div>