config/routes.rb
Rails.application.routes.draw do

# 管理者用
# URL /admin/sign_in ...
  devise_for :admin,skip:[:registrations,:passwords],controllers:{
    sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


  namespace :admin do

    root to: 'homes#top'

    resources :items ,only:[:index, :new, :create, :show, :edit, :update]

    resources :genres ,only:[:index, :create, :edit, :update]

    resources :customers ,only:[:index, :show, :edit, :update] #顧客一覧など

    resources :orders ,only:[:show, :update]

    patch '/orders/:order_id/order_details/:id' => 'order_details#update' #製作ステータスの更新　　もしくはネストはなくてもよい /admin/order_details/:id

  end

# 顧客用
# URL /customers/sign_in ...
  devise_for :customers,skip:[:passwords],controllers:{
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

    scope module: :public do

    root to: 'homes#top'
    get '/about' => 'homes#about' ,as: 'about'

    resources :items ,only:[:index, :show]

    get '/customers/my_page' => 'customers#show'
    get '/customers/information/edit' => 'customers#edit' #顧客の登録情報編集画面
    patch 'customers/information' => 'customers#update' #顧客の登録情報更新
    get '/customers/unsubscribe' => 'customers#unsubscribe' #顧客の退会確認画面
    patch '/customers/withdraw' => 'customers#withdraw' #顧客の退会処理(ステータスの更新)

    delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items ,only:[:index, :update, :create, :destroy]

    get '/orders/complete' => 'orders#complete' #注文完了画面
    resources :orders ,only:[:new, :index, :show, :create]
    post '/orders/confirm' => 'orders#confirm' #注文情報確認画面


    resources :addresses ,only:[:index, :edit, :create, :update, :destroy] #配送先情報など

  end

end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer
  
def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
end
  
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  validates :item_id, :amount, presence: true
  validates :amount, numericality: {greater_than: 0,less_than_or_equal: 10} #左記は10以下　less_thanは未満
  validates :amount, numericality:{ only_integer: true }

  def sum_price # 税込価格を算出したメソッドを定義して呼び出す taxin_priceは item.rb（税込価格)に定義
      item.with_tax_price * amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items ,dependent: :destroy
  has_many :orders ,dependent: :destroy
  has_many :addresses ,dependent: :destroy

  def full_name
    last_name+first_name
  end

  def full_name_kana
    last_name_kana+first_name_kana
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy

  validates :name, presence: true
  validates :name, {uniqueness: true}
end

#バリデーション　（モデル、view、コントローラーに記述）

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  belongs_to :genre

   def get_image(width,height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpg')
    end
    image.variant(resize_to_limit: [width, height]).processed
   end

   def with_tax_price
    (price * 1.1).floor
   end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy

  attribute :shipping_cost, :integer, default: 800


  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { waiting_payment: 0, payment_confirmation:1, production:2, preparing_to_ship:3, sent:4 }

  def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
  end

  def payment
    shipping_cost + total_payment
  end

  def full_name
    customer.last_name + customer.first_name
  end

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  enum making_status: {no_make: 0, make_wait: 1, making: 2, make_fin: 3}

  def sum_price # 税込価格を算出したメソッドを定義して呼び出す taxin_priceは item.rb（税込価格)に定義
      (price * 1.1).floor * amount
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres =Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
     redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end
  def update
    @genre =Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end

  private
   def genre_params
    params.require(:genre).permit(:name)
   end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top  #注文履歴一覧（adminのtop）
    @orders = Order.page(params[:page])
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end

  def index
    @item = Item.page(params[:page])

  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_items_path
  end

  private
   def item_params
    params.require(:item).permit(:name, :image, :introduction, :genre_id, :price, :is_active)
   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<!--以下は管理者側には、サインインの機能のみが存在しているのでそれ以外の記述を削除している-->
<%#- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%#= link_to "Sign up", new_registration_path(resource_name) %><br />
<%# end %>

<%#- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%#= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<%# end %>

<%#- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%#= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<%# end %>

<%#- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%#= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<%# end %>

<%#- if devise_mapping.omniauthable? %>
  <%#- resource_class.omniauth_providers.each do |provider| %>
    <%#= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <%# end %>
<%# end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
 <body>
  <header>
    <% if admin_signed_in? %>
     <nav class = "navbar navbar-dark bg-light "> <%# ヘッダー全ての色 %>
      <div class = "container">
       <%= link_to "LOGO" ,admin_root_path ,class: "btn btn-outline-secondary font-weight-bold " %>
        <div class = "row">
         <div class = "col ">
          <%= link_to "商品一覧", admin_items_path , class: "btn btn-outline-secondary mr-3" %>
          <%= link_to "会員一覧", admin_customers_path , class: "btn btn-outline-secondary mr-3" %>
          <%= link_to "注文履歴一覧", admin_root_path , class: "btn btn-outline-secondary mr-3" %>
          <%= link_to "ジャンル一覧", admin_genres_path , class: "btn btn-outline-secondary mr-3" %>
          <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "btn btn-outline-secondary mr-3" %>
         <div class ="input-group col-6 ml-auto mt-3"> <%# なぜautoだと右よせになる？ %>
           <input type = "text" id="txt-search" class= "form-control input-group-append " placeholder="Search" ></input>
          <span class ="input-group-btn input-group-append">
           <submit type = "submit" id ="btn-search" class="btn btn-primary"><i class ="fas fa-search"></i></submit>
          </span>
         </div>
        </div>
      </div>
     </nav>
    <% elsif customer_signed_in? %>
     <nav class = "navbar navbar-dark bg-light "> <%# ヘッダー全ての色 %>
      <div class = "container">
       <%= link_to "LOGO" ,root_path ,class: "btn btn-outline-secondary font-weight-bold " %>
        <div class = "row">
         <div class = "col ">
            <%= link_to "マイページ", customers_my_page_path, class: "btn btn-outline-secondary mr-3" %>
            <%= link_to "商品一覧", items_path, class: "btn btn-outline-secondary mr-3" %>
            <%= link_to "カート", cart_items_path, class: "btn btn-outline-secondary mr-3" %>
            <%= link_to "ログアウト" , destroy_customer_session_path, method: :delete, class: "btn btn-outline-secondary mr-3" %>
         <div class ="input-group col-6 ml-auto mt-3"> <%# なぜautoだと右よせになる？ %>
          <input type = "text" id="txt-search" class= "form-control input-group-append " placeholder="Search" ></input>
           <span class ="input-group-btn input-group-append">
            <submit type = "submit" id ="btn-search" class="btn btn-primary"><i class ="fas fa-search"></i></submit>
           </span>
         </div>
        </div>
      </div>
     </nav>
    <% else %>
     <nav class = "navbar navbar-dark bg-light "> <%# ヘッダー全ての色 %>
       <div class = "container">
        <%= link_to "LOGO" ,root_path ,class: "btn btn-outline-secondary font-weight-bold " %>
         <div class = "row">
          <div class = "col ">
            <%= link_to "About", about_path , class: "btn btn-outline-secondary mr-3 " %>
            <%= link_to "商品一覧" , items_path , class: "btn btn-outline-secondary mr-3" %>
            <%= link_to "新規登録" , new_customer_registration_path , class: "btn btn-outline-secondary mr-3" %>
            <%= link_to "ログイン" , new_customer_session_path , class: "btn btn-outline-secondary mr-3" %>
           <div class ="input-group col-6 ml-auto mt-3"> <%# なぜautoだと右よせになる？ %>
            <input type = "text" id="txt-search" class= "form-control input-group-append " placeholder="Search" ></input>
            <span class ="input-group-btn input-group-append">
             <submit type = "submit" id ="btn-search" class="btn btn-primary"><i class ="fas fa-search"></i></submit>
            </span>
           </div>
          </div>
         </div>
       </div>
     </nav>
    <% end %>
  </header>


    <%= yield %>
  </body>
</html>